import esbuild from 'esbuild';
import process from 'process';
import fs from 'node:fs';
import path from 'node:path';
import { builtinModules } from 'node:module';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';
const outDir = "result";

const staticWatchAndCopy = (targets = []) => {
	return {
		name: 'static-watch-and-copy-plugin',
		setup(build) {
			const resolvedTargets = targets.map(target => (
			{
				src: path.resolve(target.src),
				dest: path.resolve(target.dest)
			}));

			build.onLoad({ filter: /main\.ts$/ }, () => 
			{
				return {
					watchFiles: resolvedTargets.map(t => t.src), 
				};
			});
			build.onEnd(() => 
			{
				try {
					for (const target of resolvedTargets) 
					{
						const destDir = path.dirname(target.dest);
						
						if (!fs.existsSync(destDir)) {
							fs.mkdirSync(destDir, { recursive: true });
						}

						fs.copyFileSync(target.src, target.dest);

					}
				} catch (err) {
					console.error('[Static Copy Error] Error copying static files:', err.message);
				}
			});
		},
	};
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	outfile: `${outDir}/main.js`,
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	minify: prod,
	plugins: [
		staticWatchAndCopy([
			{ src: './src/styles.css', dest: `${outDir}/styles.css` },
			{ src: './manifest.json', dest: `${outDir}/manifest.json` }
		])
	]
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
